document.writeln("<!doctype html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title>广东科学技术职业学院</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("		<!--尾部-->");
document.writeln("		<div id=\'myfooter\'>");
document.writeln("			<div id=\'myfooter_hr\'></div>");
document.writeln("			<div id=\'myfooter_left\'>");
document.writeln("				<img src=\'images/index/footer-logo.png\' />");
document.writeln("			</div>");
document.writeln("			<div id=\'myfooter_right\'>");
document.writeln("				<div  >");
document.writeln("					<label> 友情链接:&nbsp;&nbsp;");
document.writeln("						<a href=\'http://www.gdstc.gov.cn/\'>广东省科技厅</a>&nbsp;&nbsp;");
document.writeln("						<a href=\'http://www.gdhed.edu.cn/\'>广东省教育厅</a> &nbsp;&nbsp;");
document.writeln("						<a href=\'http://www.zh-job.com/zhmgr/\'>珠海市人才网</a>&nbsp;&nbsp;");
document.writeln("						<a href=\'http://www.10ms.edu.cn/\'>教育网高速资源指南</a>&nbsp;&nbsp;");
document.writeln("						<a href=\'http://10.30.252.31/login.jsp?_p=YXM9MSZwPTEmbT1OJg__\'>后台登陆</a>");
document.writeln("					</label>");
document.writeln("				</div>");
document.writeln("				<div>");
document.writeln("					广州校区地址：广州市天河区科华街351号(邮编:510640) 珠海校区地址：珠海市金湾区珠海大道南侧(邮编：519090)");
document.writeln("				</div>");
document.writeln("				<div>");
document.writeln("					邮箱：webmaster@gdit.edu.cn　电话：(广州)020-85297309 (珠海)0756-7796288　传真：020-85291714");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");